# Generated by Django 4.2.4 on 2023-09-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pedido', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_pedido', models.IntegerField()),
                ('forma_de_pago', models.CharField(max_length=10)),
                ('tipo_de_pedido', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pickeador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('dni', models.IntegerField()),
                ('horario', models.CharField(max_length=20)),
            ],
        ),
    ]
