# Generated by Django 4.2.4 on 2023-09-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pedido',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
